name: Test Workflow

# ทำให้เราสามารถกดรัน workflow นี้ได้เองจากหน้าเว็บ GitHub
on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "Workflow file is visible and running!"